[tool.ruff]
line-length=121
extend-exclude = ["**/migrations/"]

[tool.ruff.lint]
extend-select=[
    "E",
    "W",
    "I",
    "N",
    "DJ",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "TRY"
]

[tool.ruff.lint.per-file-ignores]
"manage.py"= ["TRY003"]
"app/settings.py"= ["E501"]

[tool.ruff.format]
quote-style= "double"