# Generated by Django 4.2.19 on 2025-02-09 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aircraft",
            options={
                "verbose_name": "Aircraft",
                "verbose_name_plural": "Aircrafts",
            },
        ),
    ]
