# Generated by Django 4.2.19 on 2025-02-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated at"
                    ),
                ),
                (
                    "aircraft_name",
                    models.IntegerField(
                        choices=[
                            (1, "Bayraktar TB2"),
                            (2, "Bayraktar TB3"),
                            (3, "Akıncı"),
                            (4, "Kızılelma"),
                        ],
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Aircraft",
                "verbose_name_plural": "Aircrafts",
            },
        ),
    ]
