# Generated by Django 4.2.19 on 2025-02-09 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aircraft", "0002_alter_aircraft_options"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            (1, "Kanat"),
                            (2, "Gövde"),
                            (3, "Kuyruk"),
                            (4, "Aviyonik"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="aircraft.aircraft",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produced_parts",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Part",
                "verbose_name_plural": "Parts",
                "unique_together": {("name", "aircraft")},
            },
        ),
    ]
