# Generated by Django 4.2.19 on 2025-02-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="name",
            field=models.IntegerField(
                choices=[
                    (1, "Kanat"),
                    (2, "Gövde"),
                    (3, "Kuyruk"),
                    (4, "Aviyonik"),
                ],
                max_length=50,
            ),
        ),
    ]
