# Generated by Django 4.2.19 on 2025-02-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="part",
            unique_together=set(),
        ),
    ]
