# Generated by Django 4.2.19 on 2025-02-09 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aircraft", "0002_alter_aircraft_options"),
        ("part", "0002_alter_part_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assembly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assembly_at", models.DateTimeField(auto_now_add=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aircraft.aircraft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assembly",
                "verbose_name_plural": "Assemblies",
            },
        ),
        migrations.AlterField(
            model_name="part",
            name="name",
            field=models.IntegerField(
                choices=[
                    (1, "Kanat"),
                    (2, "Gövde"),
                    (3, "Kuyruk"),
                    (4, "Aviyonik"),
                ]
            ),
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="part.part",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory",
                "verbose_name_plural": "Inventories",
            },
        ),
        migrations.CreateModel(
            name="AssemblyPartUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_used", models.PositiveIntegerField()),
                (
                    "assembly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="part.assembly",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="part.part",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assembly",
            name="parts_used",
            field=models.ManyToManyField(
                through="part.AssemblyPartUsage", to="part.part"
            ),
        ),
    ]
