# Generated by Django 4.2.19 on 2025-02-09 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "part",
            "0003_assembly_alter_part_name_inventory_assemblypartusage_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="assembly",
            old_name="assembly_at",
            new_name="created_at",
        ),
    ]
